# Generated by Django 3.2.8 on 2021-11-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('original_url', models.URLField()),
                ('short_url', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
